
area:
	g++ -o bin/ch2/area src/ch2/area.cpp -lstdc++

checklimits:
	g++ -o bin/ch2/checklimits src/ch2/checklimits.cpp -lstdc++

dividebyzero:
	g++ -o bin/ch2/dividebyzero src/ch2/dividebyzero.cpp -lstdc++

